# config.toml

[network]
host = "0.0.0.0"
server_ip = "127.0.0.1"
tcp_port = 2627
udp_port = 2627

[game]
session_key = "WulframSessionKey123"
motd = "Welcome to Wulf-Forge!"
map_name = "crossroads"

[player]
player_id = 1337
name = "default"
nametag = "DEV"
team = 1
unit_type = 0

[debug]
debug_packets = true
show_ascii = false