# packets.toml

[tank]
unit_type = 0
team_id = 1 # this will change at runtime, just leaving it here for now
default_pos = [100.0, 100.0, 100.0]
default_rot = [0.0, 0.0, 0.0]

[tank.stats]
include_vitals = true
weapon_id = 0
health_mult_bits = 1
energy_mult_bits = 1

[behavior]
target_size = 3116
weapons_units_count = 4
weapon_slots_count = 13
unit_count = 39
vehicle_physics_count = 2
active_vehicles_count = 3

[behavior.header]
spawn_related = 0
timeout = 5.0
# ... add other header floats here ...
unk11 = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

[behavior.unit_defaults]
scale = 1.0
max_health = 100
regen_or_health_related = 100.0

[behavior.vehicle_physics]
speed = 20.0
accel = 8.0
engine_torque = 700
suspension_stiffness = 550 # Doesn't change much
ground_friction = 0.5 # Doesn't seem to do anything, maybe just used for hill climbing?
turn_rate = 0.2
suspension_dampening = 1.25 # Very sensitive, lower values are pretty speedy and chaotic
mass = 33000 # Doesn't change much, but very low values seem to make you heavy for some reason?

[behavior.active_vehicle_physics]
turn_adjust = 4.5
move_adjust = 125.0 # Default: 85.0
max_velocity = 80.0
gravity_pct = 0.65