# packets.toml

[tank]
unit_type = 0
team_id = 1 # this will change at runtime, just leaving it here for now
default_pos = [100.0, 100.0, 100.0]
default_rot = [0.0, 0.0, 0.0]

[tank.stats]
include_vitals = true
weapon_id = 0
health_mult_bits = 1
energy_mult_bits = 1

[behavior]
weapons_units_count = 4
weapon_slots_count = 13
unit_count = 39
vehicle_physics_count = 2
active_vehicles_count = 3

[behavior.header]
spawn_related = 0
timeout = 5.0
gravity_force = 100.0
unk11 = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

[behavior.unit_defaults]
scale = 1.0
max_health = 100
regen_or_health_related = 100.0

[behavior.vehicle_physics]
speed = 20.0            # Default: 20.0
accel = 4.0             # Default: 4.0
engine_torque = 700     # Default: 700
suspension_stiffness = 550 # Default: 550
ground_friction = 0.8   # Default: 0.8
turn_rate = 0.05        # Default: Tank: 0.05 Scout: 0.15
suspension_dampening = 1.3 # Default: Tank: 1.3 Scout: 1.1
mass = 33000            # Default: Tank: 33000 Scout: 13000

[behavior.active_vehicle_physics]
turn_adjust = 4.5   # Default: 4.5
move_adjust = 85.0  # Default: 85.0
move_backward_adjust = 38.0 # Default: 38.0 (Scout only?)
strafe_adjust = 69.7 # Default: Tank: 69.7 Scout: 72.0
max_velocity = 80.0  # Default: Tank: 80.0 Scout: 85.0
low_fuel_level = 2000.0 # Default: 2000.0
max_altitude = 3.25  # Default: Tank: 3.25 Scout: 4.9
max_speed_height_pickup = 3.5 # Default: 3.5 (Scout only?)
gravity_pct = 1.0   # Default: 1.0